name: "☀️ Daily tasks"

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      year:
        description: "Year"
        required: false
      month:
        description: "Month"
        required: false

jobs:
  run-daily-tasks:
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}

    steps:
      - name: "📦 Checkout"
        uses: actions/checkout@v3

      - name: "🍔 Set up Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "✅ Install dependencies"
        run: bun install

      - name: "🏃‍♂️ Fetch value and set on Notion with given year and month"
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli set-current-value-of-workout-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: "🏃‍♂️ Fetch value and set on Notion with default year and month"
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli set-current-value-of-workout-key-result

      - name: "🏃‍♂️ Fetch and save workout stats"
        run: bun run cli save-workout-stats-to-vault

      - name: "🗄️ Commit vault back to repo"
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: "🤖 Add workout data"
          commit_user_name: "0x4444"
          commit_user_email: "0x4444@users.noreply.github.com"
          commit_author: "0x4444 <0x4444@users.noreply.github.com>"
          file_pattern: "vault/*"
