name: "📆 Monthly tasks"

on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:
    inputs:
      year:
        description: "Year"
        required: false
      month:
        description: "Month"
        required: false

jobs:
  run-monthly-tasks:
    name: "👷 Run monthly tasks"
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}

    steps:
      - name: "📦 Checkout"
        uses: actions/checkout@v3

      - name: "🍔 Set up Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "✅ Install dependencies"
        run: bun install

      - name: "🐒 Create workout key result for given month"
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli create-monthly-workout-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: "🐒 Create workout key result for current month"
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli create-monthly-workout-key-result

      - name: "🧘 Create meditation key result for given month"
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli create-monthly-meditations-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: "🧘 Create meditation key result for current month"
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli create-monthly-meditations-key-result

      - name: "👀 Create observations key result for given month"
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli create-monthly-observations-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: "👀 Create observations key result for current month"
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli create-monthly-observations-key-result

  deploy:
    name: "☁️"
    needs: [run-monthly-tasks]
    uses: krimlabs/state-of-being/.github/workflows/cd.yml@master
    secrets: inherit
