name: "📆 Monthly tasks"

on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:
    inputs:
      year:
        description: "Year"
        required: false
      month:
        description: "Month"
        required: false

jobs:
  run-monthly-tasks:
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}

    steps:
      - name: "📦 Checkout"
        uses: actions/checkout@v3

      - name: "🍔 Set up Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "✅ Install dependencies"
        run: bun install

      - name: "🏃‍♂️ Create Key Result for given month"
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli create-monthly-workout-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: "🏃‍♂️ Create Key Result for current month"
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli create-monthly-workout-key-result
